version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=urineStripAnalyzer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=King@2203
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:15
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=urineStripAnalyzer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=King@2203
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: